#!/bin/bash

# get battery level without percentageq for math use
# BATTERY=$(acpi -b | awk -F'[, ]' '{print $5}' | tr -d "%")
BATTERY=$(acpi -b | awk '{print $4}' | grep -E -o '[0-9][0-9]')

if [[ $BATTERY -ge 80 ]]; then
	echo "  $BATTERY%"
elif [[ $BATTERY -ge 60 ]]; then
	echo "  $BATTERY%"
elif [[ $BATTERY -ge 40 ]]; then
	echo "  $BATTERY%"
elif [[ $BATTERY -ge 20 ]]; then
	echo "  $BATTERY%"	# full text
	echo "  $BATTERY%"	# small text
    echo "#FFF600"			# yellow for 20-40%
else
	echo "  $BATTERY%"	# full text
	echo "  $BATTERY%"	# small text
	echo "#FF0000"			# red for 0-20%
fi
