#!/bin/bash

# get battery level without percentageq for math use
INFO=$(acpi -b)
BATTERY=$(echo $INFO | awk '{print $4}' | grep -E -o '[0-9][0-9]')
STATE=$(echo $INFO | awk '{print $3}' | tr -d ",")

PREPEND=""

if [[ $STATE == "Charging" ]]; then
	PREPEND="+"
fi



if [[ $BATTERY -ge 80 ]]; then
	echo "  $PREPEND$BATTERY%"
elif [[ $BATTERY -ge 60 ]]; then
	echo "  $PREPEND$BATTERY%"
elif [[ $BATTERY -ge 40 ]]; then
	echo "  $PREPEND$BATTERY%"
elif [[ $BATTERY -ge 20 ]]; then
	echo "  $PREPEND$BATTERY%"	# full text
	echo "  $PREPEND$BATTERY%"	# small text
    echo "#FFF600"			# yellow for 20-40%
else
	echo "  $PREPEND$BATTERY%"	# full text
	echo "  $PREPEND$BATTERY%"	# small text
	echo "#FF0000"			# red for 0-20%
fi
