#!/bin/bash

INTERFACE="wlp58s0"

# exit if wifi is down
if [[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "disc"
    echo "disc"
    echo "#FF0000"
    exit
fi

# get network quality as a fraction
QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# iwgetid -r
SSID=$(iwgetid -r)

echo $SSID $QUALITY%	# full text
echo $QUALITY%		# short text

# change color and icon depending on network quality
if [[ $QUALITY -ge 80 ]]; then		# green for >80%
    echo "#00FF00"
elif [[ $QUALITY -ge 60 ]]; then	# yellow for >60%
    echo "#FFF600"
elif [[ $QUALITY -ge 40 ]]; then	# orange for >40%
    echo "#FFAE00"
else
    echo "#FF0000"					# red for 0-40%
fi

# whoever wrote this should be ashamed
# if [[ $QUALITY -ge 80 ]]; then
#     echo "#00FF00"
# elif [[ $QUALITY -lt 80 ]]; then
#     echo "#FFF600"
# elif [[ $QUALITY -lt 60 ]]; then
#     echo "#FFAE00"
# elif [[ $QUALITY -lt 40 ]]; then
#     echo "#FF0000"
# fi